'use strict';
const faker = require("faker");
module.exports = {
  up: (queryInterface, Sequelize) => {

      return queryInterface.bulkInsert('Spots', [
        {
          userId:1,
          address: "203-1202, Hirabari, Tempaku-ku Nagoya-shi",
          city:"Aichi",
          lat:35.1222,
          lng:137.001602,
          name:'test',
          description:faker.lorem.paragraph(),
          price:300,
          image_url:"https://res.cloudinary.com/dveuedvvm/image/upload/v1638240334/R_dgbnys.jpg" ,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          address: "5-3-10 Yamaguchi, Murayama Town",
          city:"Yagamata",
          lat:38.478810,
          lng:140.386300,
          name:'house',
          description:faker.lorem.paragraph(),
          price:400,
          image_url:"https://res.cloudinary.com/dveuedvvm/image/upload/v1638243614/1_20T3_023_zirp7n.jpg" ,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          address: "9-1-6 Saito, Kano Town",
          city:"Fukushima",
          lat:34.723991,
          lng:136.487076,
          name:'house',
          description:faker.lorem.paragraph(),
          price:150,
          image_url:"https://res.cloudinary.com/dveuedvvm/image/upload/v1638237540/blob_jou3bk.jpg" ,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:3,
          address: "265-1058, Futatsuimachi Otamote, Noshiro-shi",
          city:"Akita",
          lat:39.714687,
          lng:140.114274,
          name:'house',
          description:faker.lorem.paragraph(),
          price:299,
          image_url:"https://res.cloudinary.com/dveuedvvm/image/upload/v1638237677/blob_m7cjbk.jpg" ,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:3,
        address: "5-6-5 Hamada, Yamamoto-cho",
        city:"Fukushima",
        lat:37.749351,
        lng:140.462888,
        name:'house',
        description:faker.lorem.paragraph(),
        price:85,
        image_url:"https://res.cloudinary.com/dveuedvvm/image/upload/v1638237742/blob_vlxexq.jpg" ,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId:3,
        address: "9-6-1 Koizumi, Kondo-cho, Kobayashi",
        city:"Tokyo",
        lat:35.691784,
        lng:139.765971,
        name:'house',
        description:faker.lorem.paragraph(),
        price:500,
        image_url:"https://res.cloudinary.com/dveuedvvm/image/upload/v1638238078/blob_j2b8wr.jpg" ,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId:3,
        address: "6-10-3 Suzuki, Nakatsugawa Town",
        city:"Fukushima",
        lat:37.790293,
        lng:140.452170,
        name:'house',
        description:faker.lorem.paragraph(),
        price:125,
        image_url:"https://res.cloudinary.com/dveuedvvm/image/upload/v1638238112/blob_adkr4s.jpg" ,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId:4,
        address: "4-10-6 Sasaki, Nakamura Town",
        city:"Saitama",
        lat:35.907199,
        lng:139.637655,
        name:'house',
        description:faker.lorem.paragraph(),
        price:230,
        image_url:"https://res.cloudinary.com/dveuedvvm/image/upload/v1638238356/blob_hczxte.jpg" ,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId:4,
        address: "113-1064, Nokurosawa, Obanazawa-shi",
        city:"Yamagata",
        lat:36.907199,
        lng:139.637655,
        name:'house',
        description:faker.lorem.paragraph(),
        price:550,
        image_url:"https://res.cloudinary.com/dveuedvvm/image/upload/v1638238499/blob_srhwuf.jpg" ,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId:4,
        address: "253-1023, Yayoi, Bunkyo-ku",
        city:"Tokyo",
        lat:35.907199,
        lng:138.637655,
        name:'house',
        description:faker.lorem.paragraph(),
        price:300,
        image_url:"https://res.cloudinary.com/dveuedvvm/image/upload/v1638240405/blob_vjrste.jpg" ,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId:4,
        address: "84-1038, Nishishinjuku Shinjuku Erutawa(18-kai), Shinjuku-ku",
        city:"Tokyo",
        lat:35.907199,
        lng:137.637655,
        name:'house',
        description:faker.lorem.paragraph(),
        price:125,
        image_url:"https://res.cloudinary.com/dveuedvvm/image/upload/v1638240450/download_vqvelp.jpg" ,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId:5,
        address: "146-1300, Yotsuya 28-20-704 4-chome, Shinjuku-ku",
        city:"Yamagata",
        lat:34.907199,
        lng:136.637655,
        name:'house',
        description:faker.lorem.paragraph(),
        price:155,
        image_url:"https://res.cloudinary.com/dveuedvvm/image/upload/v1638238811/blob_oxjlan.jpg" ,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId:5,
        address: "119-1269, Momoyamacho Mino, Fushimi-ku-shi, Fushimi-ku Kyoto-shi",
        city:"Kyoto",
        lat:35.907199,
        lng:136.637655,
        name:'house',
        description:faker.lorem.paragraph(),
        price:250,
        image_url:"https://res.cloudinary.com/dveuedvvm/image/upload/v1638238976/blob_veq7ui.jpg" ,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // {
      //   userId:5,
      //   address: "299-1161, Kitashirakawa Yamadacho, Sakyo-ku-shi, Sakyo-ku Kyoto-shi",
      //   city:"Kyoto",
      //   lat:34.907199,
      //   lng:136.637655,
      //   name:'house',
      //   description:faker.lorem.paragraph(),
      //   price:600,
      //   image_url:"https://res.cloudinary.com/dveuedvvm/image/upload/v1638243702/iv7jsf8cgla1nlh6qwlp.jpg" ,
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   userId:5,
      //   address: "30-16, Ogikubo 4-chome, Suginami-ku",
      //   city:"Tokyo",
      //   lat:36.907199,
      //   lng:137.637655,
      //   name:'house',
      //   description:faker.lorem.paragraph(),
      //   price:300,
      //   image_url:"https://res.cloudinary.com/dveuedvvm/image/upload/v1638239722/blob_vhqcua.jpg" ,
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },




      ], {});
  },

  down: (queryInterface, Sequelize) => {

      return queryInterface.bulkDelete('Spots', null, {});

  }
};
