'use strict';
const faker = require("faker");
module.exports = {
  up: (queryInterface, Sequelize) => {

      return queryInterface.bulkInsert('Reviews', [
        {
          userId:1,
          spotId:1,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:1,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:1,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:1,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:1,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:1,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:1,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:2,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:1,
          spotId:2,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:2,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:2,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:2,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:2,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:2,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:2,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:2,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:1,
          spotId:3,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:3,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:3,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:3,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:3,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:3,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:3,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:3,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:1,
          spotId:4,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:4,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:4,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:4,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:4,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:4,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:4,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:4,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:1,
          spotId:5,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:5,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:5,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:5,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:5,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:5,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:5,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:5,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:1,
          spotId:6,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:6,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:6,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:6,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:6,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:6,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:6,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:6,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:1,
          spotId:7,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:7,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:7,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:7,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:7,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:7,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:7,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:7,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:1,
          spotId:8,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:8,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:8,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:8,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:8,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:8,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:8,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:8,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:1,
          spotId:9,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:9,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:9,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:9,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:9,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:9,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:9,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:9,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:1,
          spotId:10,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:10,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:10,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:10,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:10,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:10,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:10,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:10,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:1,
          spotId:11,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:11,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:11,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:11,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:11,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:11,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:11,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:11,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:1,
          spotId:12,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:12,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:12,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:12,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:12,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:12,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:12,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:12,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:1,
          spotId:13,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:13,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:13,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:13,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:13,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:13,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:13,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:13,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:1,
          spotId:14,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:14,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:14,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:14,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:14,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:14,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:14,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:14,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:1,
          spotId:15,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:15,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:15,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:15,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:15,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:15,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:15,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          spotId:15,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },




      ], {});

  },

  down: (queryInterface, Sequelize) => {

      return queryInterface.bulkDelete('Reviews', null, {});

  }
};
