'use strict';
const faker = require("faker");
module.exports = {
  up: (queryInterface, Sequelize) => {

      return queryInterface.bulkInsert('Reviews', [
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:1,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:1,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:1,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:1,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:1,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:1,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:1,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:2,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:2,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:2,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:2,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:2,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:2,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:2,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:2,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:2,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:3,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:3,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:3,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:3,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:3,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:3,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:3,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:3,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:4,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:4,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:4,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:4,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:4,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:4,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:4,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:4,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:5,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:5,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:5,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:5,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:5,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:5,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:5,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:5,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:6,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:6,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:6,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:6,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:6,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:6,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:6,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:6,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:7,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:7,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:7,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:7,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:7,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:7,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:7,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:7,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:8,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:8,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:8,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:8,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:8,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:8,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:8,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:8,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:9,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:9,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:9,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:9,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:9,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:9,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:9,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:9,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:10,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:10,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:10,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:10,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:10,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:10,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:10,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:10,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:11,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:11,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:11,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:11,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:11,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:11,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:11,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:11,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:12,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:12,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:12,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:12,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:12,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:12,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:12,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:12,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:13,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:13,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:13,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:13,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:13,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:13,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:13,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          username:faker.internet.userName(),
          spotId:13,
          review:faker.lorem.sentence(),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        // {
        //   userId:2,
        //   username:faker.internet.userName(),
        //   spotId:14,
        //   review:faker.lorem.sentence(),
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   userId:2,
        //   username:faker.internet.userName(),
        //   spotId:14,
        //   review:faker.lorem.sentence(),
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   userId:2,
        //   username:faker.internet.userName(),
        //   spotId:14,
        //   review:faker.lorem.sentence(),
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   userId:2,
        //   username:faker.internet.userName(),
        //   spotId:14,
        //   review:faker.lorem.sentence(),
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   userId:2,
        //   username:faker.internet.userName(),
        //   spotId:14,
        //   review:faker.lorem.sentence(),
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   userId:2,
        //   username:faker.internet.userName(),
        //   spotId:14,
        //   review:faker.lorem.sentence(),
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   userId:2,
        //   username:faker.internet.userName(),
        //   spotId:14,
        //   review:faker.lorem.sentence(),
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   userId:2,
        //   username:faker.internet.userName(),
        //   spotId:14,
        //   review:faker.lorem.sentence(),
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   userId:2,
        //   username:faker.internet.userName(),
        //   spotId:15,
        //   review:faker.lorem.sentence(),
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   userId:2,
        //   username:faker.internet.userName(),
        //   spotId:15,
        //   review:faker.lorem.sentence(),
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   userId:2,
        //   username:faker.internet.userName(),
        //   spotId:15,
        //   review:faker.lorem.sentence(),
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   userId:2,
        //   username:faker.internet.userName(),
        //   spotId:15,
        //   review:faker.lorem.sentence(),
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   userId:2,
        //   username:faker.internet.userName(),
        //   spotId:15,
        //   review:faker.lorem.sentence(),
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   userId:2,
        //   username:faker.internet.userName(),
        //   spotId:15,
        //   review:faker.lorem.sentence(),
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   userId:2,
        //   username:faker.internet.userName(),
        //   spotId:15,
        //   review:faker.lorem.sentence(),
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   userId:2,
        //   username:faker.internet.userName(),
        //   spotId:15,
        //   review:faker.lorem.sentence(),
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },




      ], {});

  },

  down: (queryInterface, Sequelize) => {

      return queryInterface.bulkDelete('Reviews', null, {});

  }
};
