'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {

      return queryInterface.bulkInsert('Spots', [
        {
          userId:1,
          address: "203-1202, Hirabari, Tempaku-ku Nagoya-shi",
          city:"Aichi",
          lat:35.1222,
          lng:137.001602,
          name:'test',
          price:300,
          image_url:"https://www.japan-guide.com/thumb/XYZeXYZe2158_1680b.jpg" ,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          address: "5-3-10 Yamaguchi, Murayama Town",
          city:"Yagamata",
          lat:38.478810,
          lng:140.386300,
          name:'house',
          price:300,
          image_url:"https://www.japan-guide.com/thumb/XYZeXYZe2158_1680b.jpg" ,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          address: "9-1-6 Saito, Kano Town",
          city:"Fukushima",
          lat:34.723991,
          lng:136.487076,
          name:'house',
          price:300,
          image_url:"https://www.japan-guide.com/thumb/XYZeXYZe2158_1680b.jpg" ,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
          address: "265-1058, Futatsuimachi Otamote, Noshiro-shi",
          city:"Akita",
          lat:39.714687,
          lng:140.114274,
          name:'house',
          price:300,
          image_url:"https://www.japan-guide.com/thumb/XYZeXYZe2158_1680b.jpg" ,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId:2,
        address: "5-6-5 Hamada, Yamamoto-cho",
        city:"Fukushima",
        lat:37.749351, 
        lng:140.462888,
        name:'house',
        price:300,
        image_url:"https://www.japan-guide.com/thumb/XYZeXYZe2158_1680b.jpg" ,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId:2,
        address: "9-6-1 Koizumi, Kondo-cho, Kobayashi",
        city:"Tokyo",
        lat:35.691784, 
        lng:139.765971,
        name:'house',
        price:300,
        image_url:"https://www.japan-guide.com/thumb/XYZeXYZe2158_1680b.jpg" ,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId:2,
        address: "6-10-3 Suzuki, Nakatsugawa Town",
        city:"Fukushima",
        lat:37.790293, 
        lng:140.452170,
        name:'house',
        price:300,
        image_url:"https://www.japan-guide.com/thumb/XYZeXYZe2158_1680b.jpg" ,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId:2,
        address: "4-10-6 Sasaki, Nakamura Town",
        city:"Saitama",
        lat:35.907199,
        lng:139.637655,
        name:'house',
        price:300,
        image_url:"https://www.japan-guide.com/thumb/XYZeXYZe2158_1680b.jpg" ,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId:2,
        address: "113-1064, Nokurosawa, Obanazawa-shi",
        city:"Yamagata",
        lat:null,
        lng:null,
        name:'house',
        price:300,
        image_url:"https://www.japan-guide.com/thumb/XYZeXYZe2158_1680b.jpg" ,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId:2,
        address: "253-1023, Yayoi, Bunkyo-ku",
        city:"Tokyo",
        lat:null,
        lng:null,
        name:'house',
        price:300,
        image_url:"https://www.japan-guide.com/thumb/XYZeXYZe2158_1680b.jpg" ,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId:2,
        address: "84-1038, Nishishinjuku Shinjuku Erutawa(18-kai), Shinjuku-ku",
        city:"Tokyo",
        lat:null,
        lng:null,
        name:'house',
        price:300,
        image_url:"https://www.japan-guide.com/thumb/XYZeXYZe2158_1680b.jpg" ,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId:2,
        address: "146-1300, Yotsuya 28-20-704 4-chome, Shinjuku-ku",
        city:"Yamagata",
        lat:null,
        lng:null,
        name:'house',
        price:300,
        image_url:"https://www.japan-guide.com/thumb/XYZeXYZe2158_1680b.jpg" ,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId:2,
        address: "119-1269, Momoyamacho Mino, Fushimi-ku-shi, Fushimi-ku Kyoto-shi",
        city:"Kyoto",
        lat:null,
        lng:null,
        name:'house',
        price:300,
        image_url:"https://www.japan-guide.com/thumb/XYZeXYZe2158_1680b.jpg" ,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId:2,
        address: "299-1161, Kitashirakawa Yamadacho, Sakyo-ku-shi, Sakyo-ku Kyoto-shi",
        city:"Kyoto",
        lat:null,
        lng:null,
        name:'house',
        price:300,
        image_url:"https://www.japan-guide.com/thumb/XYZeXYZe2158_1680b.jpg" ,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId:2,
        address: "30-16, Ogikubo 4-chome, Suginami-ku",
        city:"Tokyo",
        lat:null,
        lng:null,
        name:'house',
        price:300,
        image_url:"https://www.japan-guide.com/thumb/XYZeXYZe2158_1680b.jpg" ,
        createdAt: new Date(),
        updatedAt: new Date(),
      },




      ], {});
  },

  down: (queryInterface, Sequelize) => {

      return queryInterface.bulkDelete('Spots', null, {});

  }
};
